activechecks:
  anim: [unknown]
  light: [DeadUtility, unknown, UtilityNames, geoSuffix, duplicateNames, constructionHistory]
  mdl: [intermediateObject, grpSuffix, unknown, pastedNodes, animCurves, UtilityNames,
    geoSuffix, duplicateNames, transformGeometry, references, endingWith##, constructionHistory,
    shapeNames]
  rig: [intermediateObject, grpSuffix, unknown, pastedNodes, animCurves, UtilityNames,
    geoSuffix, duplicateNames, transformGeometry, references, endingWith##, constructionHistory,
    shapeNames]
checkList: [geoSuffix, duplicateNames, constructionHistory, DeadUtility, UtilityNames,
  intermediateObject, shapeNames, references, pastedNodes, animCurves, grpSuffix,
  transformGeometry, endingWith##, unknown]
rcMenu:
  DeadUtility: []
  UtilityNames: []
  animCurves: []
  constructionHistory: []
  duplicateNames: [rename, removeShapes]
  endingWith##: [rename]
  geoSuffix: [rename, AddGeoSuffix]
  grpSuffix: [rename, AddGrpSuffix]
  intermediateObject: []
  pastedNodes: []
  references: []
  shapeNames: []
  transformGeometry: []
