activechecks:
  anim: []
  light: []
  mdl: [intermediateObject, DeadUtility, nurbsCurve, grpSuffix, unknown, pastedNodes,
    animCurves, UtilityNames, geoSuffix, duplicateNames, transformGeometry, references,
    endingWith##, constructionHistory, shapeNames]
  rig: [intermediateObject, DeadUtility, nurbsCurve, grpSuffix, unknown, pastedNodes,
    animCurves, UtilityNames, geoSuffix, duplicateNames, transformGeometry, references,
    endingWith##, constructionHistory, shapeNames]
checkList: [geoSuffix, duplicateNames, constructionHistory, DeadUtility, UtilityNames,
  intermediateObject, shapeNames, references, pastedNodes, animCurves, grpSuffix,
  transformGeometry, endingWith##, unknown, nurbsCurve]
rcMenu:
  DeadUtility: []
  UtilityNames: []
  animCurves: []
  constructionHistory: []
  duplicateNames: [rename, removeShapes]
  endingWith##: [rename, AddGeoSuffix, AddGrpSuffix, AddCrvSuffix]
  geoSuffix: [rename, AddGeoSuffix]
  grpSuffix: [rename, AddGrpSuffix]
  intermediateObject: []
  nurbsCurve: [rename, AddCrvSuffix]
  pastedNodes: []
  references: []
  shapeNames: []
  transformGeometry: []
