activechecks:
  anim: [DeadUtility, UtilityNames, grpSuffix, intermediateObject, nurbsCurve, pastedNodes,
    references, shapeNames, transformGeometry, unknown]
  light: [DeadUtility, duplicateNames, geoSuffix]
  mdl: [DeadUtility, UtilityNames, animCurves, constructionHistory, duplicateNames,
    endingWith##, geoSuffix, grpSuffix, intermediateObject, nurbsCurve, pastedNodes,
    references, shapeNames, transformGeometry, unknown]
  rig: [DeadUtility, UtilityNames, animCurves, constructionHistory, duplicateNames,
    endingWith##, geoSuffix, grpSuffix, intermediateObject, nurbsCurve, pastedNodes,
    references, shapeNames, transformGeometry, unknown]
allChecks: [DeadUtility, UtilityNames, animCurves, constructionHistory, duplicateNames,
  endingWith##, geoSuffix, grpSuffix, intermediateObject, nurbsCurve, pastedNodes,
  references, shapeNames, transformGeometry, unknown]
rightClickCheckSubMenus:
  DeadUtility: []
  UtilityNames: []
  animCurves: []
  constructionHistory: [constructionHistory]
  duplicateNames: [rename, removeShapes]
  endingWith##: [rename, AddGeoSuffix, AddGrpSuffix, AddCrvSuffix]
  geoSuffix: [rename, AddGeoSuffix]
  grpSuffix: [rename, AddGrpSuffix]
  intermediateObject: []
  nurbsCurve: [rename, AddCrvSuffix]
  pastedNodes: []
  references: []
  shapeNames: []
  transformGeometry: []
  unknown: []
