activechecks:
  anim: []
  light: []
  mdl: []
  rig: []
  srf: []
allChecks: [DeadUtility, UtilityNames, animCurves, constructionHistory, duplicateNames,
  endingWith##, geoSuffix, grpSuffix, intermediateObject, nurbsCurve, pastedNodes,
  references, shapeNames, transformGeometry, unknown]
buttons:
  anim: {icon: iconmonstr-direction-10-240, toolTip: Set checks for animation dept}
  light: {icon: iconmonstr-light-bulb-16-240, toolTip: Set checks for lighting dept}
  mdl: {icon: iconmonstr-cube-11-240, toolTip: Set checks for modeling dept}
  rig: {icon: iconmonstr-magic-6-240, toolTip: Set checks for rig dept}
  srf: {icon: iconmonstr-paint-bucket-12-240, toolTip: Set checks for surfacing dept}
rightClickCheckSubMenus:
  DeadUtility: []
  UtilityNames: []
  animCurves: []
  constructionHistory: [constructionHistory]
  duplicateNames: [rename, removeShapes]
  endingWith##: [rename, AddGeoSuffix, AddGrpSuffix, AddCrvSuffix]
  geoSuffix: [rename, AddGeoSuffix]
  grpSuffix: [rename, AddGrpSuffix]
  intermediateObject: []
  nurbsCurve: [rename, AddCrvSuffix]
  pastedNodes: []
  references: []
  shapeNames: [renameShape]
  transformGeometry: []
  unknown: []
