checks:
    rig:
        - geoSuffix
        - duplicateNames
        - constructionHistory
        - DeadUtility
        - UtilityNames
        - intermediateObject
        - shapeNames
        - references
        - pastedNodes
        - animCurves
        - grpSuffix
        - transformGeometry
        - endingWith##
    anim:
        - pastedNodes
        - animCurves
    mdl:
        - pastedNodes
        - animCurves
        - endingWith##
    light:
        - duplicateNames
        - DeadUtility
        - UtilityNames
        - pastedNodes
        - endingWith##

rcMenu:
    geoSuffix:
        - rename
        - AddGeoSuffix

    duplicateNames:
        - rename
        - removeShapes

    constructionHistory: []

    DeadUtility: []

    UtilityNames: []

    intermediateObject: []

    shapeNames: []

    references: []

    pastedNodes: []

    animCurves: []

    grpSuffix:
        - rename
        - AddGrpSuffix

    transformGeometry: []

    endingWith##:
        - rename
